### ISSUE TITLE
Domain name for site

### ISSUE THREAD

**Issue by ranilplus** [ranilplus/NuTreesense#1]
select domain name i'll update price list

**Comment by brlfernando** [comment]
Dear Ranil,
I need the following web site registered ASAP.
www.nutreesense.com
The following emails are also required.
info@
piyumi@
ananda@
accounts@
Regards,
Rukshan

**Comment by ranilplus** [comment]
Domain name :http://nutreesense.com/  is ok now.

http://nutreesense.com/webmail

username are your emails and passwords are send to your email.
